# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Hello World

on:
  schedule:
    - cron:  '10 7 * * *'

jobs:
  job1:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: List directory contents 
        run: dir 
      - name: Check Java version 
        run: java -version
