# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Hello World

on:
 push

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
         sparse-checkout: |  # 仅检出需要的文件夹
          /*
          !src/main/resources           # 忽略 resources
         sparse-checkout-cone-mode: false  # 允许复杂排除规则 
      - name: List directory contents 
        run: dir 
        shell: cmd
      - name: List src directory contents 
        run: | 
         cd src/main
         dir 
        shell: cmd
      - name: Check Java version 
        run: java -version
        shell: cmd
